# Generated by Django 5.2.5 on 2025-09-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(default='00000', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_number',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='gcash_name',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='gcash_number',
            field=models.CharField(default='000000', max_length=20),
            preserve_default=False,
        ),
    ]
