# Generated by Django 5.2.5 on 2025-09-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_bank_name_alter_profile_bank_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='jymcebrian@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
