# Generated by Django 5.2.5 on 2025-09-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='JOHN JOHN JOHN', max_length=50),
            preserve_default=False,
        ),
    ]
