# Generated by Django 5.2.5 on 2025-09-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_timelog_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='work_type_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
