# Generated by Django 5.2.5 on 2025-09-02 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0002_workassignment_logs_is_active_in_user'),
        ('user_account', '0003_timelog_work_type_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelogs', to='admin_account.worktype'),
        ),
    ]
