# Generated by Django 5.2.5 on 2025-09-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='logs_is_active_in_user',
            field=models.BooleanField(default=True),
        ),
    ]
